name: Build and Publish Trigger

on: 
  pull_request:
    branches: [dev, main]
    paths-ignore: 
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'

env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository

jobs:
  checkPaths:
  runs-on: ubuntu-latest
  steps: 
  - uses: dorny/paths-filter@v2
    id: filter
    with:
      filters: |
        abstractions:
          - 'components/abstractions/**'
        authentication-azure:
          - 'components/authentication/azure/**'
        http-okHttp:
          - 'components/http/okHttp/**'
        serialization-json:
          - 'components/serialization/json/**'
        serialization-text:
          - 'components/serialization/text/**' 
  
  buildAbstractions:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.abstractions_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      componentPath: ./components/abstractions/

  buildAuthenticationAzure:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.authentication-azure_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      componentPath: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.http-okHttp_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      componentPath: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.serialization-json_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      componentPath: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.serialization-text_count }} > 0 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      componentPath: ./components/serialization/text/

  publishAbstractions:
    needs: buildAbstractions
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      componentPath: ./components/abstractions/

  publishAuthenticationAzure: 
    needs: buildAuthenticationAzure
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      componentPath: ./components/authentication/azure/

  publishOkhttp:
    needs: buildOkHttp
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      componentPath: ./components/http/okHttp/
  
  publishSerializationJson:
    needs: buildSerializationJson
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      componentPath: ./components/serialization/json/
  
  publishSerializationText:
    needs: buildSerializationText
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      componentPath: ./components/serialization/text/

    