name: Build and Publish Trigger

on: 
  push:
    branches: [dev, main]
    paths-ignore: 
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
  workflow_dispatch:
    inputs:
      abstractions:
        description: release abstractions
        type: boolean
        default: false
        required: false
      authentication-azure:
        description: release azure-auth
        type: boolean
        default: false
        required: false
      http-okHttp:
        description: release http-okHttp
        type: boolean
        default: false
        required: false
      serialization-json: 
        description: release serialization-json
        type: boolean 
        default: false
        required: false
      serialization-text: 
        description: release serialization-text
        type: boolean
        default: false
        required: false
  
env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository

jobs:
  checkPaths:
    runs-on: ubuntu-latest
    outputs:
      abstractions: ${{ steps.filter.outputs.abstractions }}
      authentication-azure: ${{ steps.filter.outputs.authentication-azure }}
      http-okHttp: ${{ steps.filter.outputs.http-okHttp }}
      serialization-json: ${{ steps.filter.serialization-json }}
      serialization-text: ${{ steps.filter.serialization-text }}
    steps:
    - uses: actions/checkout@v3
    - name: checkPaths
      uses: dorny/paths-filter@v2.10.2
      id: filter
      with:
        base: main
        filters: |
          abstractions:
            - 'components/abstractions/**'
          authentication-azure:
            - 'components/authentication/azure/**'
          http-okHttp:
            - 'components/http/okHttp/**'
          serialization-json:
            - 'components/serialization/json/**'
          serialization-text:
            - 'components/serialization/text/**' 

  buildAbstractions:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.abstractions == 'true' || github.event.inputs.abstractions == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      workingDirectory: ./components/abstractions/

  buildAuthenticationAzure:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.authentication-azure == 'true' || github.event.inputs.authentication-azure == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      workingDirectory: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.http-okHttp == 'true' || github.event.inputs.http-okHttp == 'true') }}
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      workingDirectory: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.serialization-json == 'true' || github.event.inputs.serialization-json == 'true') }}
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      workingDirectory: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.serialization-text == 'true' || github.event.inputs.serialization-text == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      workingDirectory: ./components/serialization/text/

  publishAbstractions:
    needs: buildAbstractions
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/abstractions/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishAuthenticationAzure: 
    needs: buildAuthenticationAzure
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/authentication/azure/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishOkhttp:
    needs: buildOkHttp
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/http/okHttp/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}
  
  publishSerializationJson:
    needs: buildSerializationJson
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/serialization/json/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishSerializationText:
    needs: buildSerializationText
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/serialization/text/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}
    
