name: Build and Publish Trigger

on: 
  push:
    branches: [dev, main]
    paths-ignore: 
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
  workflow_dispatch:
    inputs:
      abstractions:
        description: release abstractions
        default: false
        type: boolean
      auth-azure:
        description: release azure-auth
        default: false
        type: boolean
      http-okHttp:
        description: release http-okHttp
        default: false
        type: boolean
      serialization-json: 
        description: release serialization-json
        default: false
        type: boolean 
      serialization-text: 
        description: release serialization-text
        default: false
        type: boolean
        
  
env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository

jobs:
  checkPaths:
    # if: ( github.event_name != 'workflow_dispatch'	)
    runs-on: ubuntu-latest
    steps: 
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: main
        filters: |
          abstractions:
            - 'components/abstractions/**'
          authentication-azure:
            - 'components/authentication/azure/**'
          http-okHttp:
            - 'components/http/okHttp/**'
          serialization-json:
            - 'components/serialization/json/**'
          serialization-text:
            - 'components/serialization/text/**' 

  buildAbstractions:
    needs: checkPaths
    if: ( ${{ needs.checkPaths.outputs.abstractions_count }} > 0 ) || ( github.event.inputs.abstractions == 'true' ) 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      workingDirectory: ./components/abstractions/

  buildAuthenticationAzure:
    needs: checkPaths
    if: ( ${{ needs.checkPaths.outputs.authentication-azure_count }} > 0 ) || ( github.event.inputs.auth-azure == 'true' )
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      workingDirectory: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    if: ( ${{ needs.checkPaths.outputs.http-okHttp_count }} > 0 ) || ( github.event.inputs.http-okHttp == 'true' )
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      workingDirectory: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    if: ( ${{ needs.checkPaths.outputs.serialization-json_count }} > 0 ) || ( github.event.inputs.serialization-json == 'true' )
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      workingDirectory: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    if: ( ${{ needs.checkPaths.outputs.serialization-text_count }} > 0 ) || ( github.event.inputs.serialization-text == 'true' )
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      workingDirectory: ./components/serialization/text/

  publishAbstractions:
    needs: buildAbstractions
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/abstractions/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishAuthenticationAzure: 
    needs: buildAuthenticationAzure
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/authentication/azure/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishOkhttp:
    needs: buildOkHttp
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/http/okHttp/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}
  
  publishSerializationJson:
    needs: buildSerializationJson
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/serialization/json/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}

  publishSerializationText:
    needs: buildSerializationText
    uses: ./.github/workflows/release-component.yml
    with:
      shouldPreview: ${{ github.ref == 'refs/heads/main' }}
      #shouldRelease: ${{ github.ref == 'refs/heads/main' }}
      enviornment: maven_central_snapshot
      workingDirectory: ./components/serialization/text/
    secrets:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      SECRING_GPG: ${{ secrets.SECRING_GPG }}
    
