name: Gradle Build Project Trigger

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
    workflow_dispatch:

jobs:
  checkPaths:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          abstractions:
            - 'components/abstractions/**'
          authentication-azure:
            - 'components/authentication/azure/**'
          http-okHttp:
            - 'components/http/okHttp/**'
          serialization-json:
            - 'components/serialization/json/**'
          serialization-text:
            - 'components/serialization/text/**'  
    - name: checkSecrets
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: '.\local.properties'
    - name: checkSecrets2
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.SECRING.GPG }}
        OUTPUT_PATH: '.\secring.gpg'
      
    
  buildAbstractions:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.abstractions_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      componentPath: ./components/abstractions/

  buildAuthentication:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.authentication-azure_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      componentPath: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.http-okHttp_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      componentPath: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.serialization-json_count }} > 0
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      componentPath: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    if: ${{ needs.checkPaths.outputs.serialization-text_count }} > 0 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      componentPath: ./components/serialization/text/