name: Gradle Build Projects

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
    workflow_dispatch:

    jobs:
      Build:
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Get Changed Files
            id: changed-files
            uses: tj-actions/changed-files@v22.2
          - name: build-abstractions
            if: contains(steps.changed-files.outputs.modified_files, '**components/abstractions/**')
            uses: ./.github/workflows/gradleBuild-component.yml
            with:
              componentName: abstractions
              componentPath: ./components/abstractions/
          - name: build-authentication
            if: contains(steps.changed-files.outputs.modified_files, '**components/authentication/azure/**')
            uses: ./.github/workflows/gradleBuild-component.yml
            with:
              componentName: authentication-azure
              componentPath: ./components/authentication/azure/           
          - name: build-http-okHttp
            if: contains(steps.changed-files.outputs.modified_files, '**components/http/okHttp/**')
            uses: ./.github/workflows/gradleBuild-component.yml
            with:
              componentName: http-okHttp
              componentPath: ./components/http/okHttp/
          - name: build-serialization-json
            if: contains(steps.changed-files.outputs.modified_files, '**components/serialization/json/**')
            uses: ./.github/workflows/gradleBuild-component.yml
            with:
              componentName: serialization-json
              componentPath: ./components/serialization/json/
          - name: build-serialization-text  
            if: contains(steps.changed-files.outputs.modified_files, '**components/serialization/text/**')
            uses: ./.github/workflows/gradleBuild-component.yml
            with:
              componentName: serialization-text
              componentPath: ./components/serialization/text/