name: Gradle Build Project Trigger

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
  workflow_dispatch:
    inputs:
      abstractions:
        description: build abstractions
        type: boolean
        default: false
        required: false
      authentication-azure:
        description: build azure-auth
        type: boolean
        default: false
        required: false
      http-okHttp:
        description: build http-okHttp
        type: boolean
        default: false
        required: false
      serialization-json: 
        description: build serialization-json
        type: boolean 
        default: false
        required: false
      serialization-text: 
        description: build serialization-text
        type: boolean  
        default: false
        required: false

jobs:
  checkPaths:
    runs-on: ubuntu-latest
    outputs: 
      abstractions: ${{ steps.filter.outputs.abstractions }}
      authentication-azure: ${{ steps.filter.outputs.authentication-azure }}
      http-okHttp: ${{ steps.filter.outputs.http-okHttp }}
      serialization-json: ${{ steps.filter.serialization-json }}
      serialization-text: ${{ steps.filter.serialization-text }}
    steps: 
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2.10.2
      id: filter
      with:
        filters: |
          abstractions:
            - 'components/abstractions/**'
          authentication-azure:
            - 'components/authentication/azure/**'
          http-okHttp:
            - 'components/http/okHttp/**'
          serialization-json:
            - 'components/serialization/json/**'
          serialization-text:
            - 'components/serialization/text/**'  
    - name: checkSecrets
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: '.\local.properties'
    - name: checkSecrets2
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
        OUTPUT_PATH: '.\secring.gpg'
       
  buildAbstractions:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.abstractions == 'true' || github.event.inputs.abstractions == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      workingDirectory: ./components/abstractions/

  buildAuthentication:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.authentication-azure == 'true' || github.event.inputs.authentication-azure == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      workingDirectory: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.http-okHttp == 'true' || github.event.inputs.http-okHttp == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      workingDirectory: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.serialization-json == 'true' || github.event.inputs.serialization-json == 'true') }}  
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      workingDirectory: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    if: ${{ always() && (needs.checkPaths.outputs.serialization-text == 'true' || github.event.inputs.serialization-text == 'true') }} 
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      workingDirectory: ./components/serialization/text/
