name: Gradle Build Project Trigger

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
  workflow_dispatch:

jobs:
  checkPaths:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: checkSecrets
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: '.\local.properties'
    - name: checkSecrets2
      run: .\components\abstractions\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
        OUTPUT_PATH: '.\secring.gpg'
       
  buildAbstractions:
    needs: checkPaths
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: abstractions
      workingDirectory: ./components/abstractions/

  buildAuthentication:
    needs: checkPaths
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: authentication-azure
      workingDirectory: ./components/authentication/azure/

  buildOkHttp:
    needs: checkPaths
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: http-okHttp 
      workingDirectory: ./components/http/okHttp/

  buildSerializationJson:
    needs: checkPaths
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-json
      workingDirectory: ./components/serialization/json/

  buildSerializationText:
    needs: checkPaths
    uses: ./.github/workflows/gradleBuild-component.yml
    with:
      componentName: serialization-text
      workingDirectory: ./components/serialization/text/
