name: Gradle Build Projects

on:
  pull_request:
    branches: [dev, main]
    paths-ignore:
      - '**.gradle/wrapper'
      - '**.gitignore'
      - 'LICENSE'
      - 'THIRD PARTY NOTICES'
      - '**.md'
    workflow_dispatch:

    jobs:
      Build:
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
          - name: Get Changed Files
            id: changed-files
            uses: tj-actions/changed-files@v22.2

          - name: build-abstractions
            if: contains(steps.changed-files.outputs.modified_files, '**components/abstractions/**')


          - name: build-authentication
          - name: build-http
          - name: build-serialization-json
          - name: build-serialization-tex  
