name: Release Component

on: 
  workflow_call:
    inputs:
      shouldPreview:
        required: true
        type: string
      shouldRelease: 
        required: false
        type: string
      enviornment:
        required: true
        type: string        
      workingDirectory:
        required: true
        type: string
    secrets:
      LOCAL_PROPERTIES:
        required: true
      SECRING_GPG:
        required: true
        
env: 
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository

jobs: 
  mavenSnapshot:
    if: ${{ inputs.shouldPreview }} == 'true'
    environment: 
      name: ${{ inputs.enviornment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }} 
    steps: 
      - uses: actions/checkout@v3
      - name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Download file
        run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
        shell: pwsh
        env:  
          ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
          OUTPUT_PATH: '.\local.properties' 
      - name: Download file
        run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
        shell: pwsh
        env: 
          ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
          OUTPUT_PATH: '.\secring.gpg'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew $PREVIEW_TASK
