name: Gradle Build and Publish

on:
  workflow_dispatch:
  push:
    tags: ['v*']
    branches: ['main']

env:
  PREVIEW_TASK: publishSnapshotPublicationToSonatypeSnapshotRepository
  PUBLISH_TASK: publishMavenCentralReleasePublicationToSonatypeRepository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with: 
        java-version: 17
        distribution: 'adopt'
        cache: gradle
    - name: Detect Secrets
      uses: RobertFischer/detect-secrets-action@v2.0.0
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: '.\local.properties' 
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env: 
        ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
        OUTPUT_PATH: '.\secring.gpg'
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
    - name: Publish Preview
      if: github.ref == 'refs/heads/main'
      run: ./gradlew --no-daemon $PREVIEW_TASK
    - name: Publish Release
      if: contains(github.ref, 'refs/tags/v')
      run: ./gradlew --no-daemon $PUBLISH_TASK
    - name: Release
      if: contains(github.ref, 'refs/tags/v')
      uses: anton-yurchenko/git-release@v5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
