name: Gradle Build and Publish

on:
  workflow_dispatch:
  push:
    tags: ['v*']
    branches: ['main']

env:
  PREVIEW_TASK: publishMavenPublicationToSonatypeSnapshotRepository
  PUBLISH_TASK: publishMavenPublicationToSonatypeRepository

jobs:
  release-to-maven-central-snapshot:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: maven_central_snapshot
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with: 
        java-version: 17
        distribution: 'adopt'
        cache: gradle
    - name: Detect Secrets
      uses: RobertFischer/detect-secrets-action@v2.0.0
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: 'local.properties'
      working-directory: ./
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env: 
        ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
        OUTPUT_PATH: 'secring.gpg'
      working-directory: ./
    - name: Copy secring
      run: |
        cp secring.gpg components/abstractions/ -Verbose
        cp secring.gpg components/authentication/azure/ -Verbose
        cp secring.gpg components/serialization/form/ -Verbose
        cp secring.gpg components/serialization/text/ -Verbose
        cp secring.gpg components/serialization/json/ -Verbose
        cp secring.gpg components/http/okHttp/ -Verbose
      shell: pwsh
      working-directory: ./
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
      working-directory: ./
    - name: Publish Preview
      run: ./gradlew --no-daemon $PREVIEW_TASK
      working-directory: ./
  release-to-maven-central:
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: maven_central
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with: 
        java-version: 17
        distribution: 'adopt'
        cache: gradle
    - name: Detect Secrets
      uses: RobertFischer/detect-secrets-action@v2.0.0
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env:  
        ENCODED_VALUE: ${{ secrets.LOCAL_PROPERTIES }}
        OUTPUT_PATH: 'local.properties' 
      working-directory: ./
    - name: Download file
      run: .\scripts\decodeAndWrite.ps1 -encodedValue $env:ENCODED_VALUE -outputPath $env:OUTPUT_PATH
      shell: pwsh
      env: 
        ENCODED_VALUE: ${{ secrets.SECRING_GPG }}
        OUTPUT_PATH: 'secring.gpg'
      working-directory: ./
    - name: Copy secring
      run: |
        cp secring.gpg components/abstractions/ -Verbose
        cp secring.gpg components/authentication/azure/ -Verbose
        cp secring.gpg components/serialization/form/ -Verbose
        cp secring.gpg components/serialization/text/ -Verbose
        cp secring.gpg components/serialization/json/ -Verbose
        cp secring.gpg components/http/okHttp/ -Verbose
      shell: pwsh
      working-directory: ./
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
      working-directory: ./
    - name: Publish Release
      run: ./gradlew --no-daemon $PUBLISH_TASK -PmavenCentralSnapshotArtifactSuffix=""
      working-directory: ./
    - name: Release
      uses: anton-yurchenko/git-release@v5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
